# Site settings
title: Fergies Hairdryer - Another Man Utd blog
brand: Fergies Hairdryer
email: info@fergieshairdryer.com
description: Another Man Utd blog. Analysis and views on the Red Devils.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fergieshairdryer.com" # the base hostname & protocol for your site
twitter_username: fergiesHD
analytics: UA-37809237-1
paginate: 1

# Build settings
markdown: kramdown

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets
    - _assets/fonts
    - _assets/javascript
    - _assets/stylesheets
    - _assets/images
  css_compressor: sass

exclude: ["vendor"]