# Site settings
title: Fergies Hairdryer - Another Man Utd blog
brand : Fergies Hairdryer
email: info@fergieshairdryer.com
description: > # this means to ignore newlines until "baseurl:"
  Fergies Hairdryer is a simple Man Utd blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fergieshairdryer.com" # the base hostname & protocol for your site
twitter_username: fergies_hd

# Build settings
markdown: kramdown

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets
    - _assets/fonts
    - _assets/javascript
    - _assets/stylesheets
    - _assets/images
  css_compressor: sass

exclude: ["vendor"]